### ISSUE TITLE
AppleDict-src: incorrect expected output XML

### ISSUE THREAD

**Issue by soshial** [ilius/pyglossary-test#2]
The file `appledict-src/002-no-morphology-v2/002-no-morphology-v2.xml` is incorrect, @ilius. It has tabilations removed and duplicated tags -- those shouldn't be.

I added a tabfile (test input) and an AppleDict XML (expected output) here: https://github.com/ilius/pyglossary-test/tree/c1de06bbf37225792c75eed58e7a223ffca8dfe3/appledict-src

**Comment by soshial** [comment]
I hope that after we successfully merge my morphology support, we will not need these test files, right?

**Comment by ilius** [comment]
Fixed it and added as v3.
Thanks.
